version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

conda:
  environment: conda/env.yaml

python:
  version: 3.8
  install:
    # install symupy itself
    - method: pip
      path: .
